--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.2.23.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 2021. 04. 17. 11:22:56
-- Server version: 5.5.5-10.4.11-MariaDB
-- Client version: 4.1
--


SET NAMES 'utf8';

--
-- Deleting data from table match3.jatszma_0
--
TRUNCATE TABLE match3.jatszma_0;
--
-- Inserting data into table match3.jatszma_0
--
INSERT INTO match3.jatszma_0(X, Y, csempe_id) VALUES
(0, 0, 6),
(1, 0, 2),
(2, 0, 2),
(3, 0, 4),
(4, 0, 4),
(5, 0, 4),
(6, 0, 5),
(7, 0, 4),
(0, 1, 6),
(1, 1, 0),
(2, 1, 0),
(3, 1, 3),
(4, 1, 5),
(5, 1, 6),
(6, 1, 1),
(7, 1, 1),
(0, 2, 6),
(1, 2, 7),
(2, 2, 4),
(3, 2, 5),
(4, 2, 1),
(5, 2, 5),
(6, 2, 1),
(7, 2, 5),
(0, 3, 1),
(1, 3, 0),
(2, 3, 1),
(3, 3, 6),
(4, 3, 2),
(5, 3, 4),
(6, 3, 2),
(7, 3, 4),
(0, 4, 4),
(1, 4, 7),
(2, 4, 6),
(3, 4, 2),
(4, 4, 6),
(5, 4, 0),
(6, 4, 2),
(7, 4, 3),
(0, 5, 0),
(1, 5, 5),
(2, 5, 7),
(3, 5, 2),
(4, 5, 5),
(5, 5, 1),
(6, 5, 5),
(7, 5, 3),
(0, 6, 5),
(1, 6, 4),
(2, 6, 6),
(3, 6, 7),
(4, 6, 2),
(5, 6, 4),
(6, 6, 6),
(7, 6, 4),
(0, 7, 3),
(1, 7, 4),
(2, 7, 7),
(3, 7, 7),
(4, 7, 3),
(5, 7, 0),
(6, 7, 7),
(7, 7, 0);